<a href="https://colab.research.google.com/github/ciepielajan/Time_series/blob/main/Time_series_LSTM_univariate_basic_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

In [82]:
# univariate LSTM example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [83]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [113]:
# define input sequence
raw_seq = [ i for i in range(0,110,10)]
# choose a number of time steps
n_steps = 3

In [114]:
# split into samples
X, y = split_sequence(raw_seq, n_steps)
X.shape, y.shape

((8, 3), (8,))

In [115]:
y

array([ 30,  40,  50,  60,  70,  80,  90, 100])

In [116]:
X

array([[ 0, 10, 20],
       [10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70],
       [60, 70, 80],
       [70, 80, 90]])

In [117]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
X

array([[[ 0],
        [10],
        [20]],

       [[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]],

       [[70],
        [80],
        [90]]])

In [118]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)

In [119]:
# demonstrate prediction
x_input = array([100, 110, 120])
x_input = x_input.reshape((1, n_steps, n_features))
x_input

array([[[100],
        [110],
        [120]]])

In [120]:
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[133.12192]]
